services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"  
    environment:
      MINIO_ROOT_USER: minioaccesskey
      MINIO_ROOT_PASSWORD: miniosecretkey
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  mem_api:
    build:
      context: ./mem_api
      dockerfile: Dockerfile
    env_file:
      -  ./mem_api/.env
    container_name: mem_api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - minio

  mem_store:
    build:
      context: ./mem_store
      dockerfile: Dockerfile
    container_name: mem_store
    ports:
      - "8001:8001"
    depends_on:
      - minio

volumes:
  postgres_data:
  minio_data:
