services:
  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mem_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"  # для панели управления
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  mem_api:
    build:
      context: ./mem_api
      dockerfile: Dockerfile
    container_name: mem_api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - minio
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@postgres:5432/memesdb
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin

  mem_store:
    build:
      context: ./mem_store
      dockerfile: Dockerfile
    container_name: mem_store
    ports:
      - "8001:8001"
    depends_on:
      - minio
    environment:
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin

volumes:
  postgres_data:
  minio_data:
