[tool.poetry]
name = "mem-store"
version = "0.1.0"
description = ""
authors = ["Ira <ira.ivashko.99@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
minio = "^7.2.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
